In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('main_data.csv')

In [3]:
data

movie_id                                     title  \
0        19995                                    Avatar   
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4801      9367                               El Mariachi   
4802     72766                                 Newlyweds   
4803    231617                 Signed, Sealed, Delivered   
4804    126186                          Shanghai Calling   
4805     25975                         My Date with Drew   

                                                   tags  
0     in the 22nd century, a paraplegic marine is di...  
1     captain barbossa, long believed to be dead, ha...  
2     a cryptic message from bond’s past sends him o...  
3     following the death of district attorney harve...  
4     john carter is a war-weary, former military ca...  
...                                                 ...  
4801  el mariachi just wants to play his guitar and ...  
4802  a newlywed couple's honeymoon is upended by th...  
4803  "signed, sealed, delivered" introduces a dedic...  
4804  when ambitious new york attorney sam is sent t...  
4805  ever since the second grade when he first saw ...  

[4806 rows x 3 columns]

In [4]:
import nltk
#Stemming and lemmatization
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [5]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
#         print(y)
        
    return " ".join(y)

In [6]:
#apply stem function to all the rows in tags collum
data['tags'] = data['tags'].apply(stem)

In [7]:
data['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
# get the top 5000 most common word in tags
# remove all the stop words Ex: is, a, to, etc...
cv = CountVectorizer(max_features=5000, stop_words='english')
# cv = CountVectorizer()

In [9]:
##implement countVertor
#cv.fit_transform(data['tags']).toarray().shape

##First movie
# cv.fit_transform(data['tags']).toarray()[0]
# cv.fit_transform(data['tags']).toarray()[0][412]


cv.fit_transform(data['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [10]:
## print index of '3d' in tags of the first movie
# cv.get_feature_names().index('battle')

## print all top 5000 most common word
cv.get_feature_names()

/Users/duyvo/opt/anaconda3/envs/myDataScience/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult'

In [11]:
vectors = cv.fit_transform(data['tags']).toarray()

In [12]:
vectors.shape

(4806, 5000)

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

In [14]:
#create 5000 dimension of 2D space (using word)
#In each 2D of dimension ( between 2 words ), 
#we have the vector for every movie ( using bags of word: frequency repeating)
#calcualate the similarity of each movie with the total movie in each pair of dimension
#1 is exactly the same
#0 is completely different

# cosine_similarity(vectors)[0]
cosine_similarity(vectors)

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [15]:
similarity = cosine_similarity(vectors)

In [16]:
#similarity of the first movie - Avatar (index 0)
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [17]:
data.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  in the 22nd century, a parapleg marin is dispa...  
1  captain barbossa, long believ to be dead, ha c...  
2  a cryptic messag from bond’ past send him on a...  
3  follow the death of district attorney harvey d...  
4  john carter is a war-weary, former militari ca...

In [18]:
# data['title'] == 'Avatar'
# data[data['title'] == 'Avatar']

data[data['title'] == 'Avatar'].index[0]

0

In [19]:
#if we only sort using the similarity at each index, we will mess up the index of each movie
# sorted(similarity[0], reverse = True)

#using enumerate to store index number to keep track of the movie
sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x : x[1])

[(0, 1.0000000000000002),
 (1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574),
 (582, 0.24511108480187255),
 (1204, 0.24455799402225922),
 (1194, 0.2367785320221084),
 (61, 0.23179316248638276),
 (778, 0.23174488732966075),
 (4048, 0.2278389747471728),
 (1920, 0.2252817784447915),
 (2786, 0.21853668936906193),
 (172, 0.21239769762143662),
 (972, 0.2108663315950723),
 (322, 0.2105263157894737),
 (2333, 0.20443988269091456),
 (3608, 0.20437977982832192),
 (260, 0.20395079136182276),
 (151, 0.2029530274475215),
 (4192, 0.2029530274475215),
 (1444, 0.20277677641345318),
 (74, 0.2024645717996314),
 (1089, 0.2020475485519274),
 (3675, 0.1979082783981174),
 (973, 0.19767387315371682),
 (577, 0.1976738731537168),
 (47, 0.19672236884115843),
 (2971, 0.19252140716412977),
 (942, 0.19134594929397597),
 (495, 0.19088542889273336),
 (1201, 0.19088542889273336),
 (305, 0.19007487139298027),
 (4, 0.18929940971

In [20]:
#get only five movie to recommend
sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x : x[1])[1:6]

[(1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574)]

In [21]:
#recommend function
def recommend(movie):
    #find the index of the movie 
    movie_index = data[data['title'] == movie].index[0]
    
    #find distance between the input movie with other movies
    distance = similarity[movie_index]
    
    #find 5 recommended movies list
    movies_list = sorted(list(enumerate(distance)), reverse = True, key = lambda x : x[1])[1:6]
    
    for i in movies_list:
        print(data.iloc[i[0]].title)
#         print(data.iloc[i[0]].movie_id)

In [22]:
#find the data of the movie

# data.iloc[0]
data.iloc[0].title

'Avatar'

In [23]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.


In [24]:
#converting a Python object into a byte stream to store it in a file/database, 
#maintain program state across sessions, or transport data over the network.
import pickle

In [25]:
#export movies data for using to deploy
pickle.dump(data, open('movies.pkl', 'wb'))

In [26]:
data['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [27]:
#export similarity data for using to deploy
pickle.dump(similarity, open('similarity.pkl', 'wb'))